apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: crm-microservices-apigateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: crm-system
spec:
  selector:
    app: apigateway
  ports:
  - port: 80
    targetPort: 80
