apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: crm-system
type: Opaque
data:
  auth-connection-string: SG9zdD1hdXRoLWRiOyBEYXRhYmFzZT1hdXRoX2RiOyBVc2VybmFtZT1wb3N0Z3JlczsgUGFzc3dvcmQ9c2VjcmV0
  client-connection-string: SG9zdD1jbGllbnQtZGI7IERhdGFiYXNlPWNsaWVudF9kYjsgVXNlcm5hbWU9cG9zdGdyZXM7IFBhc3N3b3JkPXNlY3JldA==
  order-connection-string: SG9zdD1vcmRlci1kYjsgRGF0YWJhc2U9b3JkZXJfZGI7IFVzZXJuYW1lPXBvc3RncmVzOyBQYXNzd29yZD1zZWNyZXQ=
  task-connection-string: SG9zdD10YXNrLWRiOyBEYXRhYmFzZT10YXNrX2RiOyBVc2VybmFtZT1wb3N0Z3JlczsgUGFzc3dvcmQ9c2VjcmV0
  twilio-connection-string: SG9zdD10d2lsaW8tZGI7IERhdGFiYXNlPXR3aWxpby1kYjsgVXNlcm5hbWU9cG9zdGdyZXM7IFBhc3N3b3JkPXNlY3JldA==
