version: "3.9"

services:
  frontend:
    build:
      context: ./CrmFront
      dockerfile: Dockerfile
    container_name: crm_frontend
    ports:
      - "3000:80"
    depends_on:
      - apigateway
    networks:
      - crm_network

  twilio-db:
    image: postgres:16
    container_name: twilio_postgres
    environment:
      POSTGRES_DB: twilio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5448:5432"
    volumes:
      - twilio_pgdata:/var/lib/postgresql/data
    networks:
      - crm_network

  auth-db:
    image: postgres:16
    container_name: auth_postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5444:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    networks:
      - crm_network

  client-db:
    image: postgres:16
    container_name: client_postgres
    environment:
      POSTGRES_DB: client_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5447:5432"
    volumes:
      - client_pgdata:/var/lib/postgresql/data
    networks:
      - crm_network

  order-db:
    image: postgres:16
    container_name: order_postgres
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5445:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data
    networks:
      - crm_network

  task-db:
    image: postgres:16
    container_name: task_postgres
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5446:5432"
    volumes:
      - task_pgdata:/var/lib/postgresql/data
    networks:
      - crm_network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - crm_network

  twilioservice:
    build:
      context: .
      dockerfile: TwilioService/TwilioService/Dockerfile
    depends_on:
      - twilio-db
      - redis
    networks:
      - crm_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=twilio-db;Database=twilio_db;Username=postgres;Password=secret
      - ConnectionStrings__Redis=redis:6379
      - IS_DOCKER=true

  authservice:
    build:
      context: .
      dockerfile: AuthService/AuthService/Dockerfile
    depends_on:
      - auth-db
      - redis
    networks:
      - crm_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=auth-db;Database=auth_db;Username=postgres;Password=secret
      - ConnectionStrings__Redis=redis:6379
      - IS_DOCKER=true

  clientservice:
    build:
      context: .
      dockerfile: ClientService/ClientService/Dockerfile
    depends_on:
      - client-db
      - redis
    networks:
      - crm_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=client-db;Database=client_db;Username=postgres;Password=secret
      - ConnectionStrings__Redis=redis:6379
      - IS_DOCKER=true

  orderservice:
    build:
      context: .
      dockerfile: OrderService/OrderService/Dockerfile
    depends_on:
      - order-db
      - redis
    networks:
      - crm_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=order-db;Database=order_db;Username=postgres;Password=secret
      - ConnectionStrings__Redis=redis:6379
      - IS_DOCKER=true

  taskservice:
    build:
      context: .
      dockerfile: TaskService/TaskService/Dockerfile
    depends_on:
      - task-db
      - redis
    networks:
      - crm_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=task-db;Database=task_db;Username=postgres;Password=secret
      - ConnectionStrings__Redis=redis:6379
      - IS_DOCKER=true

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile
    depends_on:
      - authservice
      - clientservice
      - orderservice
      - taskservice
      - redis
    ports:
      - "5241:80"
    networks:
      - crm_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - IS_DOCKER=true

networks:
  crm_network:
    driver: bridge

volumes:
  auth_pgdata:
  client_pgdata:
  order_pgdata:
  task_pgdata:
  twilio_pgdata:
  clientComments_pgdata:
