syntax = "proto3";

option csharp_namespace = "CRMSolution.Grpc.Users";

package users;

service UserService {
  rpc FindUser (FindUserRequest) returns (FindUserResponse);
  rpc GetUserById (GetUserByIdRequest) returns (GetUserByIdResponse);
}

message FindUserRequest {
  string email = 1;
  int32 orderId = 2;
}

message FindUserResponse {
  int32 id = 1;
  string username = 2;
  string email = 3;
  int32 role = 4;
  bool IsEmailConfirmed = 5;
}

message GetUserByIdRequest {
  int32 id = 1;
}

message GetUserByIdResponse {
  int32 id = 1;
  string username = 2;
  string email = 3;
  int32 role = 4;
}
