export const restaurants = [ 
    { 
      id: 1, 
      name: "Rose Garden Restaurant", 
      rating: 4.7, 
      delivery: "Free", 
      time: "20 min", 
      categories: ["Burger", "Chicken", "Rice", "Wings"], 
      image: "https://source.unsplash.com/400x300/?restaurant,1", 
    }, 
    { 
      id: 2, 
      name: "Spicy Delight", 
      rating: 4.5, 
      delivery: "$2", 
      time: "25 min", 
      categories: ["Indian", "Curry", "Spicy", "Rice"], 
      image: "https://source.unsplash.com/400x300/?restaurant,2", 
    }, 
    { 
      id: 3, 
      name: "Pizza Plaza", 
      rating: 4.6, 
      delivery: "Free", 
      time: "15 min", 
      categories: ["Pizza", "Italian", "Cheese", "Bread"], 
      image: "https://source.unsplash.com/400x300/?pizza", 
    }, 
    { 
      id: 4, 
      name: "Sushi Time", 
      rating: 4.8, 
      delivery: "$3", 
      time: "30 min", 
      categories: ["Sushi", "Japanese", "Fish", "Rice"], 
      image: "https://source.unsplash.com/400x300/?sushi", 
    }, 
    { 
      id: 5, 
      name: "Burger House", 
      rating: 4.3, 
      delivery: "Free", 
      time: "22 min", 
      categories: ["Burger", "Fries", "Drinks", "Beef"], 
      image: "https://source.unsplash.com/400x300/?burger", 
    }, 
    { 
      id: 6, 
      name: "Green Bowl", 
      rating: 4.6, 
      delivery: "$1", 
      time: "18 min", 
      categories: ["Salad", "Healthy", "Vegetarian", "Bowl"], 
      image: "https://source.unsplash.com/400x300/?salad", 
    }, 
    { 
      id: 7, 
      name: "Taco Fiesta", 
      rating: 4.4, 
      delivery: "Free", 
      time: "19 min", 
      categories: ["Taco", "Mexican", "Spicy", "Corn"], 
      image: "https://source.unsplash.com/400x300/?taco", 
    }, 
    { 
      id: 8, 
      name: "Pasta Point", 
      rating: 4.5, 
      delivery: "$2", 
      time: "27 min", 
      categories: ["Pasta", "Italian", "Tomato", "Cheese"], 
      image: "https://source.unsplash.com/400x300/?pasta", 
    }, 
    { 
      id: 9, 
      name: "Kebab King", 
      rating: 4.2, 
      delivery: "$2", 
      time: "35 min", 
      categories: ["Kebab", "Grill", "Middle Eastern", "Spices"], 
      image: "https://source.unsplash.com/400x300/?kebab", 
    }, 
    { 
      id: 10, 
      name: "Veggie Heaven", 
      rating: 4.9, 
      delivery: "Free", 
      time: "20 min", 
      categories: ["Vegetarian", "Organic", "Vegan", "Smoothies"], 
      image: "https://source.unsplash.com/400x300/?vegan,restaurant", 
    }, 
    { 
      id: 11, 
      name: "Seafood Spot", 
      rating: 4.7, 
      delivery: "$3", 
      time: "28 min", 
      categories: ["Seafood", "Fish", "Shrimp", "Rice"], 
      image: "https://source.unsplash.com/400x300/?seafood", 
    }, 
    { 
      id: 12, 
      name: "Noodle Nook", 
      rating: 4.3, 
      delivery: "Free", 
      time: "17 min", 
      categories: ["Noodles", "Asian", "Spicy", "Vegetables"], 
      image: "https://source.unsplash.com/400x300/?noodles", 
    }, 
    { 
      id: 13, 
      name: "BBQ Brothers", 
      rating: 4.6, 
      delivery: "$2", 
      time: "24 min", 
      categories: ["BBQ", "Ribs", "Chicken", "Beef"], 
      image: "https://source.unsplash.com/400x300/?bbq", 
    }, 
    { 
      id: 14, 
      name: "Waffle World", 
      rating: 4.1, 
      delivery: "Free", 
      time: "21 min", 
      categories: ["Waffles", "Dessert", "Sweet", "Breakfast"], 
      image: "https://source.unsplash.com/400x300/?waffles", 
    }, 
    { 
      id: 15, 
      name: "Curry Corner", 
      rating: 4.5, 
      delivery: "$1", 
      time: "23 min", 
      categories: ["Curry", "Indian", "Spicy", "Naan"], 
      image: "https://source.unsplash.com/400x300/?curry", 
    }, 
    { 
      id: 16, 
      name: "Fried Chicken Hub", 
      rating: 4.2, 
      delivery: "$2", 
      time: "26 min", 
      categories: ["Chicken", "Fried", "Fast Food", "Wings"], 
      image: "https://source.unsplash.com/400x300/?friedchicken", 
    }, 
    { 
      id: 17, 
      name: "Wrap & Roll", 
      rating: 4.0, 
      delivery: "Free", 
      time: "22 min", 
      categories: ["Wrap", "Rolls", "Snacks", "Street Food"], 
      image: "https://source.unsplash.com/400x300/?wrap", 
    }, 
    { 
      id: 18, 
      name: "Döner Delight", 
      rating: 4.3, 
      delivery: "Free", 
      time: "25 min", 
      categories: ["Döner", "Turkish", "Lamb", "Wrap"], 
      image: "https://source.unsplash.com/400x300/?doner", 
    }, 
    { 
      id: 19, 
      name: "Pancake Palace", 
      rating: 4.4, 
      delivery: "$1", 
      time: "18 min", 
      categories: ["Pancakes", "Breakfast", "Sweet", "Fruit"], 
      image: "https://source.unsplash.com/400x300/?pancakes", 
    }, 
    { 
      id: 20, 
      name: "Bistro Fresh", 
      rating: 4.6, 
      delivery: "Free", 
      time: "20 min", 
      categories: ["Bistro", "Modern", "Salad", "Healthy"], 
      image: "https://source.unsplash.com/400x300/?bistro", 
    }, 
  ]; 